### ISSUE TITLE
Version of Python

### ISSUE THREAD

**Issue by cjpotgieter** [ScalefreeCOM/turbovault4dbt#30]
I am experiencing errors trying to install python modules needed. "Failed building wheel ..." Historically I have seen this if the version of python needs to be a lower version. Any suggestions?

**Comment by universe-designer** [comment]
I had a similiar error. The cause was that my updated python installation (3.8 -> 3.12) was not compatible with the already installed python modules.
I reinstalled my virtual python environment. 

```
python -m venv dbt-env 
dbt-env\Scripts\activate
python -m ensurepip --upgrade
python -m pip install --upgrade pip
python -m pip install --upgrade setuptools
dbt-env\Scripts\python -m pip install --upgrade -r requirements.txt

```


My requirements.txt file looks like this:

```
dbt-oracle
pandas
gooey
openpyxl
```

**Comment by cjpotgieter** [comment]
I just installed the modules I needed
